'use server';

import { createTable, Column, getTablesForProject } from '@/lib/data';

export async function createTableAction(formData: FormData) {
  const tableName = formData.get('tableName') as string;
  const description = formData.get('description') as string;
  const projectId = formData.get('projectId') as string;
  const columnsStr = formData.get('columns') as string;

  if (!tableName || !projectId || !columnsStr) {
    return { error: 'Missing required fields.' };
  }

  if (!/^[a-zA-Z0-9_]+$/.test(tableName)) {
    return { error: 'Table name can only contain letters, numbers, and underscores.' };
  }

  try {
    // Check for duplicate table name
    const existingTables = await getTablesForProject(projectId);
    if (existingTables.some(t => t.table_name.toLowerCase() === tableName.toLowerCase())) {
      return { success: false, error: `A table with the name '${tableName}' already exists in this project.` };
    }

    // Parse columns from the request (expected format: "name:type,name2:type2")
    // In Phase 2, we map these simple types to our strict Firestore types.
    const validTypes = ['int', 'varchar', 'boolean', 'date', 'float', 'timestamp', 'now()'];

    const columns: Column[] = columnsStr.split(',').map(c => {
      const [name, rawType] = c.split(':');
      let type = rawType?.trim().toLowerCase();
      let defaultValue: string | undefined = undefined;

      // simple normalization for the UI's simple input format
      if (type === 'text' || type === 'string') type = 'varchar';
      if (type === 'number' || type === 'integer') type = 'int';
      if (type === 'bool') type = 'boolean';

      // Handle 'now()' magic type
      if (type === 'now()') {
        type = 'timestamp';
        defaultValue = 'now()';
      }

      if (!name || !validTypes.includes(type) && type !== 'timestamp') { // checking timestamp again as we might have just set it
        // For now, default to VARCHAR if unknown, to be safe during migration
        // Unless it was explicitly validated above
        if (!['int', 'varchar', 'boolean', 'date', 'float', 'timestamp'].includes(type)) {
          type = 'varchar';
        }
      }

      return {
        column_id: '', // will be generated by createTable
        table_id: '', // will be set by createTable
        column_name: name.trim(),
        data_type: type.toUpperCase() as any,
        is_primary_key: false, // Default for now
        is_nullable: true,
        default_value: defaultValue
      };
    });

    if (columns.length === 0) {
      return { error: 'You must define at least one column.' };
    }

    const table = await createTable(projectId, tableName, description || '', columns);
    return { success: true, tableId: table.table_id };

  } catch (error) {
    console.error('Table creation failed:', error);
    return { error: `An unexpected error occurred: ${(error as Error).message}` };
  }
}
